// Generated by Selenium IDE
package edu.pitt.cs;
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1LINKS() {
    driver.get("http://localhost:8080/");
    //driver.get("https://cs1632-buggier.appspot.com/");

    //on the buggier version the url does not have the /reset on the end of it
    //need to check that the reset tag is not included/is present or not
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    
    // create list and find the href for /reset
    List<WebElement> elements = driver.findElements(By.xpath("//nav//a[text()='Reset']")); //-> need to check for location in the link itself
    
    // check that the href is exactly "/reset"
    String resetHref = elements.get(0).getAttribute("href");
    assertEquals("http://localhost:8080/reset", resetHref);
  }
  @Test
  public void tEST2RESET() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    js.executeScript("document.cookie = \"1=true\"; document.cookie = \"2=true\"; document.cookie = \"3=true\";");
    driver.findElement(By.xpath("//a[contains(@href, \'/reset\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'ID 1. Jennyanydots\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'ID 2. Old Deuteronomy\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'ID 3. Mistoffelees\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST3CATALOG() {
    //driver.get("https://cs1632-buggier.appspot.com/");
    driver.get("http://localhost:8080/");

    //this test was not working because it also wanted to check the ORDER of images
    //so needs to be more specific that the second image is the cat2.jpg since in the buggier
    //version the images are in a different order
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    
    driver.findElement(By.xpath("//a[contains(text(),'Catalog')]")).click();

    // find all images in the catalog
    List<WebElement> images = driver.findElements(By.tagName("img"));

    // pull out the second image's src attribute - should be the cat2.jpg
    String secondImageSrc = images.get(1).getAttribute("src");

    // second image is cat2.jpg
    assertEquals("http://localhost:8080/images/cat2.jpg", secondImageSrc);
  }
  @Test
  public void tEST4LISTING() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    driver.findElement(By.xpath("//a[contains(text(),\'Catalog\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'listing\']/ul/li[3]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'listing\']/ul/li[4]"));
      assert(elements.size() == 0);
    }
    assertThat(driver.findElement(By.xpath("//div[@id=\'listing\']/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST5RENTACAT() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    driver.findElement(By.xpath("//a[contains(text(),\'Rent-A-Cat\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Rent\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Return\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST6RENT() {
    //driver.get("https://cs1632-buggier.appspot.com/");
    //this fails on the buggier version because the rental list is out of order
    //so need to check that the items appear in the right order
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");

    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.id("rentID")).click();
    driver.findElement(By.id("rentID")).sendKeys("1");
    driver.findElement(By.xpath("//button[contains(text(),'Rent')]")).click();

    // get only relevant list items based on known texts
    List<WebElement> relevantCats = driver.findElements(By.xpath("//li[contains(text(), 'Rented out') or contains(text(), 'ID 2. Old Deuteronomy') or contains(text(), 'ID 3. Mistoffelees')]"));

    // should be three items in the listing
    assertEquals(3, relevantCats.size());

    // make sure the order of the listing is exactly like postconditions
    assertEquals("Rented out", relevantCats.get(0).getText().trim());
    assertEquals("ID 2. Old Deuteronomy", relevantCats.get(1).getText().trim());
    assertEquals("ID 3. Mistoffelees", relevantCats.get(2).getText().trim());

    // check success message
    WebElement successMsg = driver.findElement(By.id("rentResult"));
    assertEquals("Success!", successMsg.getText().trim());
  }
  @Test
  public void tEST7RETURN() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie = \"3=false\";");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.id("returnID")).click();
    driver.findElement(By.id("returnID")).sendKeys("2");
    driver.findElement(By.cssSelector(".form-group:nth-child(4) .btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'ID 1. Jennyanydots\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'ID 2. Old Deuteronomy\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[contains(.,\'ID 3. Mistoffelees\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'returnResult\']"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Reset")).click();
  }
  @Test
  public void tEST8FEEDACAT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Reset")).click();
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Feed\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST9FEED() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    driver.findElement(By.id("catnips")).click();
    driver.findElement(By.id("catnips")).sendKeys("6");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.textToBePresentInElementLocated(By.id("feedResult"), "Nom, nom, nom."));
      
      List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\'feedResult\' and text()=\'Nom, nom, nom.\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST10GREETACAT() {
    driver.get("http://localhost:8080/");
    driver.findElement(By.linkText("Greet-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//h4[contains(.,\'Meow!Meow!Meow!\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//h4[contains(.,\'Meow! from Jennyanydots.\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void dEFECT1FUNFEED() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    driver.findElement(By.xpath("//a[contains(text(),\'Feed-A-Cat\')]")).click();
    driver.findElement(By.xpath("//input[@id=\'catnips\']")).click();
    driver.findElement(By.xpath("//input[@id=\'catnips\']")).sendKeys("0");
    driver.findElement(By.xpath("//button[contains(.,\'Feed\')]")).click();
    driver.findElement(By.xpath("//div[@id=\'feedResult\']")).click();

    //need to wait for page to refresh with Nom nom
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
    wait.until(ExpectedConditions.textToBePresentInElementLocated(By.id("feedResult"), "Nom, nom, nom."));

    //the test now fails because the expected is Cat fight! but the actual is Nom, nom, nom
    assertThat(driver.findElement(By.xpath("//div[@id=\'feedResult\']")).getText(), is("Cat fight!"));
  }
}
